### PR TITLE
Support animation property

### PR DESCRIPTION
**Pull request by skinnyjames**
This PR supports the animation property in https://github.com/kottenator/jquery-circle-progress.
It also emits a vue event on the circle's initialization.

### CODE REVIEW

**Comment by vrajroham** [comment]
@skinnyjames Thanks alot for taking your time. I'll review and merge the PR soon.

Cheers :tada:

**Comment by skinnyjames** [comment]
@vrajroham no problem!  
I actually reworked the format of how the boxes are made (using a slot instead of inner-text) in order to show the percentage and other html at the same time.

I'll will probably be using this route to fit my needs, if you wanted to take a look at it and were interested, I'd be happy to rework or make a PR.

https://github.com/skinnyjames/vue-circle-progress/tree/idea

**Comment by skinnyjames** [comment]
@vrajroham no problem!  
I actually reworked the format of how the boxes are made (using a slot instead of inner-text) in order to show the percentage and other html at the same time.

I'll will probably be using this route to fit my needs, if you wanted to take a look at it and were interested, I'd be happy to rework or make a PR.

https://github.com/skinnyjames/vue-circle-progress/tree/idea

**Comment by vrajroham** [comment]
@skinnyjames Thanks for your contribution. You are the first contributor to this library.
Also I pulled and merged your `slot` feature in repo. See #2 

Cheers :tada:

**Comment by vrajroham** [comment]
Just released new version to npm with your contribution! 

@skinnyjames If you are interested I can add you as contributor, so you can freely work around without my intervention. Let me know!

**Comment by skinnyjames** [comment]
Sure! I can work on docs, issues, or optimizations.

**Comment by vrajroham** [comment]
Hope you would have got invitation link. :+1: 

If you are interested in VueJS stuff and libraries then, below are some libraries where active development is going on and you can learn much more things there.

---

https://github.com/rowanwins/vue-dropzone
https://github.com/vrajroham/vue-simple-lightbox

**Comment by skinnyjames** [comment]
Great, I'll check it out

**Pull request merged**
