### PR TITLE
Memory leak

### PR DESCRIPTION
**Pull request by skinnyjames**
jquery-easing was wrapping jquery as well as it being included.
This caused memory leaks, true apologies.
jquery.easing will extend the included jquery.

### CODE REVIEW

**Comment by vrajroham** [comment]
No problem! 👍

**Comment by skinnyjames** [comment]
I'd just like to double verify that everything works ok with the changes!
Sorry again.

**Comment by vrajroham** [comment]
No worry! Take your time. Hope you will be able to release update version
to npm. Else revert me I'll publish in morning

**Comment by skinnyjames** [comment]
@vrajroham - Changes pushed! Looks stable.  I'm not sure what the process is on publishing to npm, I think i need a user.

**Comment by vrajroham** [comment]
@skinnyjames It's too easy. 
Before that 1 more thing, Never commit you `package-lock.json` file to master branch or any branch. Because It's just intended for you. (Before publish to master branch always delete `package-lock.json`)
### Steps to publish on npm
- Create account on [npm](https://www.npmjs.com/signup) (try to keep same username as of github, but not mandatory).
- Login to npm - `$npm login` (Enter username, password and email, you will be logged in)
- Got to project root.
- It seems you already updated the version to `1.1.1` as you fixed the bug.
- If you are logged ion to npm then just hit `npm publish`

That's it!

**Comment by skinnyjames** [comment]
@vrajroham Sounds good!
I don't have access to publish this repository however.  
`npm ERR! You do not have permission to publish "vue2-circle-progress"`

I believe you can add collaborators through npm via https://docs.npmjs.com/cli/owner

**Comment by vrajroham** [comment]
Opps! My bad. 

**Done!** :tada:

**Pull request merged**
